apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
  labels:
    app: mysql-pod
spec:
  containers:
    - name: mysql-pod
      image: mysql
      ports:
        - containerPort: 3306
      env:
      - name: MYSQL_ROOT_PASSWORD
        value: "123456"